#!/usr/bin/env node
/**
 * Cordova iOS hooks for Face Recognition:
 * - after_prepare / before_build: write build-extras.xcconfig + sign script
 * - after_build: re-sign Face Recognition frameworks inside the built .app
 */
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');


const IOS_BUNDLE_ID = 'com.identixia.facerecognitionsdk.app';


function readTeamId(projectRoot) {
  if (process.env.DEVELOPMENT_TEAM) return process.env.DEVELOPMENT_TEAM;
  const buildJson = path.join(projectRoot, 'build.json');
  if (!fs.existsSync(buildJson)) return null;
  try {
    const cfg = JSON.parse(fs.readFileSync(buildJson, 'utf8'));
    return (
      cfg?.ios?.debug?.developmentTeam ||
      cfg?.ios?.release?.developmentTeam ||
      null
    );
  } catch {
    return null;
  }
}


function writeExtras(projectRoot, teamId) {
  const cordovaDir = path.join(projectRoot, 'platforms', 'ios', 'cordova');
  if (!fs.existsSync(cordovaDir)) return;
  const lines = [
    '// Auto-generated by face-recognition-cordova hooks/ios_prepare.js',
    `PRODUCT_BUNDLE_IDENTIFIER = ${IOS_BUNDLE_ID}`,
    'CODE_SIGN_STYLE = Automatic',
  ];
  if (teamId) lines.push(`DEVELOPMENT_TEAM = ${teamId}`);
  fs.writeFileSync(
    path.join(cordovaDir, 'build-extras.xcconfig'),
    lines.join('\n') + '\n'
  );


  const pbx = path.join(
    projectRoot,
    'platforms',
    'ios',
    'App.xcodeproj',
    'project.pbxproj'
  );
  if (fs.existsSync(pbx)) {
    let text = fs.readFileSync(pbx, 'utf8');
    text = text.replace(
      /PRODUCT_BUNDLE_IDENTIFIER = "?[^";\n]+"?;/g,
      `PRODUCT_BUNDLE_IDENTIFIER = ${IOS_BUNDLE_ID};`
    );
    if (teamId) {
      if (/DEVELOPMENT_TEAM = /.test(text)) {
        text = text.replace(
          /DEVELOPMENT_TEAM = [^;]+;/g,
          `DEVELOPMENT_TEAM = ${teamId};`
        );
      } else if (/CODE_SIGN_STYLE = Automatic;/.test(text)) {
        text = text.replace(
          /CODE_SIGN_STYLE = Automatic;/g,
          `CODE_SIGN_STYLE = Automatic;\n\t\t\t\tDEVELOPMENT_TEAM = ${teamId};`
        );
      }
    }
    fs.writeFileSync(pbx, text);
  }
}


function writeSignScript(platformsIos) {
  const scriptsDir = path.join(platformsIos, 'scripts');
  fs.mkdirSync(scriptsDir, { recursive: true });
  const dest = path.join(scriptsDir, 'sign_nested_facerecognitionsdk.sh');
  fs.writeFileSync(
    dest,
    `#!/bin/bash
set -euo pipefail
# Usage: sign_nested_facerecognitionsdk.sh <Frameworks-dir> [identity]
DEST="\${1:?Frameworks folder required}"
ID="\${2:-\${EXPANDED_CODE_SIGN_IDENTITY:-}}"
if [ -z "\$ID" ] || [ "\$ID" = "-" ]; then
  ID=\$(security find-identity -v -p codesigning 2>/dev/null | awk -F'"' '/Apple Development|iPhone Developer/{print \$2; exit}')
fi
if [ -z "\$ID" ]; then
  echo "error: no code signing identity" >&2
  exit 1
fi
sign_one() {
  local fw="\$1"
  [ -d "\$fw" ] || return 0
  if [ -d "\$fw/Frameworks" ]; then
    for nested in "\$fw/Frameworks"/*.framework; do
      [ -d "\$nested" ] || continue
      sign_one "\$nested"
    done
  fi
  echo "Signing \$(basename "\$fw") with \$ID"
  /usr/bin/codesign --remove-signature "\$fw" 2>/dev/null || true
  /usr/bin/codesign --force --sign "\$ID" --timestamp=none "\$fw"
}
signed=0
for name in facerecognitionsdk FaceRecognitionEngine onnxruntime; do
  fw="\$DEST/\$name.framework"
  if [ -d "\$fw" ]; then
    sign_one "\$fw"
    signed=1
  fi
done
if [ "\$signed" -eq 0 ]; then
  echo "error: no Face Recognition frameworks in \$DEST" >&2
  exit 1
fi
`,
    { mode: 0o755 }
  );
}


function findApps(projectRoot) {
  const ios = path.join(projectRoot, 'platforms', 'ios');
  const hits = [];
  function walk(dir, depth) {
    if (depth > 6 || !fs.existsSync(dir)) return;
    for (const name of fs.readdirSync(dir)) {
      const full = path.join(dir, name);
      let st;
      try {
        st = fs.lstatSync(full);
      } catch {
        continue;
      }
      if (st.isSymbolicLink()) continue;
      if (name.endsWith('.app') && st.isDirectory()) hits.push(full);
      else if (st.isDirectory() && name !== 'node_modules') walk(full, depth + 1);
    }
  }
  walk(ios, 0);
  return hits;
}


/**
 * Cordova/Xcode can rewrite relative framework symlinks (e.g. onnxruntime ->
 * libonnxruntime.dylib) into absolute paths pointing at the plugin source.
 * Absolute symlinks are rejected on-device (ios-deploy 0xe8000005 /
 * CoreDevice SZExtractorError).
 */
function fixAbsoluteSymlinks(rootDir) {
  if (!fs.existsSync(rootDir)) return 0;
  let fixed = 0;
  function walk(dir, depth) {
    if (depth > 12) return;
    let entries;
    try {
      entries = fs.readdirSync(dir);
    } catch {
      return;
    }
    for (const name of entries) {
      const full = path.join(dir, name);
      let st;
      try {
        st = fs.lstatSync(full);
      } catch {
        continue;
      }
      if (st.isSymbolicLink()) {
        let target;
        try {
          target = fs.readlinkSync(full);
        } catch {
          continue;
        }
        if (!path.isAbsolute(target)) continue;
        const resolved = path.resolve(path.dirname(full), target);
        const dirOfLink = path.dirname(full);
        // Prefer a same-directory relative link when the basename exists locally.
        const localCandidate = path.join(dirOfLink, path.basename(resolved));
        let newTarget = null;
        if (fs.existsSync(localCandidate) && !fs.lstatSync(localCandidate).isSymbolicLink()) {
          newTarget = path.basename(resolved);
        } else if (resolved.startsWith(dirOfLink + path.sep) || resolved === dirOfLink) {
          newTarget = path.relative(dirOfLink, resolved);
        }
        if (!newTarget || newTarget.startsWith('..' + path.sep + '..')) {
          // If target exists under this framework tree, still relativize.
          if (fs.existsSync(resolved)) {
            newTarget = path.relative(dirOfLink, resolved);
          } else {
            continue;
          }
        }
        if (!newTarget || path.isAbsolute(newTarget)) continue;
        fs.unlinkSync(full);
        fs.symlinkSync(newTarget, full);
        fixed += 1;
        console.log(
          `[face-recognition-cordova] fixed symlink ${full} -> ${newTarget}`
        );
      } else if (st.isDirectory()) {
        walk(full, depth + 1);
      }
    }
  }
  walk(rootDir, 0);
  return fixed;
}


function fixIosSymlinks(projectRoot) {
  const ios = path.join(projectRoot, 'platforms', 'ios');
  const n = fixAbsoluteSymlinks(ios);
  if (n > 0) {
    console.log(`[face-recognition-cordova] rewrote ${n} absolute symlink(s)`);
  }
}


/** Keep platforms/plugin frameworks in sync with Identixia/src/ios/Frameworks. */
function syncPluginFrameworks(projectRoot) {
  const srcRoot = path.join(
    projectRoot,
    'Identixia',
    'src',
    'ios',
    'Frameworks'
  );
  if (!fs.existsSync(srcRoot)) return;
  const dests = [
    path.join(
      projectRoot,
      'platforms',
      'ios',
      'App',
      'Plugins',
      'face-recognition-cordova'
    ),
    path.join(
      projectRoot,
      'plugins',
      'face-recognition-cordova',
      'src',
      'ios',
      'Frameworks'
    ),
  ];
  let copied = 0;
  for (const destRoot of dests) {
    if (!fs.existsSync(destRoot)) continue;
    for (const name of [
      'facerecognitionsdk',
      'FaceRecognitionEngine',
      'onnxruntime',
    ]) {
      const src = path.join(srcRoot, `${name}.framework`);
      const dest = path.join(destRoot, `${name}.framework`);
      if (!fs.existsSync(src)) continue;
      fs.rmSync(dest, { recursive: true, force: true });
      fs.cpSync(src, dest, { recursive: true });
      copied += 1;
    }
  }
  if (copied > 0) {
    console.log(
      '[face-recognition-cordova] synced iOS frameworks into platforms/plugins'
    );
  }
}


function resignAppPreservingEntitlements(appPath) {
  const idOut = spawnSync(
    'security',
    ['find-identity', '-v', '-p', 'codesigning'],
    { encoding: 'utf8' }
  );
  const match = (idOut.stdout || '').match(
    /"(Apple Development[^"]+|iPhone Developer[^"]+)"/
  );
  const identity = match ? match[1] : null;
  if (!identity) return;
  // Leading ":" forces XML output (raw blob cannot be fed back to codesign).
  const entFile = path.join(
    require('os').tmpdir(),
    `fr-cordova-entitlements-${process.pid}.plist`
  );
  spawnSync('codesign', ['-d', `--entitlements=:${entFile}`, appPath], {
    encoding: 'utf8',
  });
  const args = ['--force', '--sign', identity, '--timestamp=none'];
  if (fs.existsSync(entFile) && fs.statSync(entFile).size > 0) {
    args.push(`--entitlements=${entFile}`);
  } else {
    args.push('--preserve-metadata=identifier,entitlements,flags,runtime');
  }
  args.push(appPath);
  const r = spawnSync('codesign', args, { stdio: 'inherit' });
  try {
    fs.unlinkSync(entFile);
  } catch {
    // ignore
  }
  if (r.status !== 0) {
    console.warn(
      `[face-recognition-cordova] warning: could not re-sign ${appPath} (status=${r.status})`
    );
  } else {
    console.log(`[face-recognition-cordova] re-sealed ${path.basename(appPath)}`);
  }
}


function signBuiltApps(projectRoot) {
  const script = path.join(
    projectRoot,
    'platforms',
    'ios',
    'scripts',
    'sign_nested_facerecognitionsdk.sh'
  );
  if (!fs.existsSync(script)) {
    writeSignScript(path.join(projectRoot, 'platforms', 'ios'));
  }
  fixIosSymlinks(projectRoot);
  const apps = findApps(projectRoot);
  let signed = 0;
  for (const app of apps) {
    const dest = path.join(app, 'Frameworks');
    if (!fs.existsSync(dest)) continue;
    fixAbsoluteSymlinks(app);
    console.log(`[face-recognition-cordova] re-signing frameworks in ${dest}`);
    const r = spawnSync('/bin/sh', [script, dest], { stdio: 'inherit' });
    if (r.status !== 0) process.exit(r.status == null ? 1 : r.status);
    // Nested fw re-sign invalidates the outer app seal — restore with entitlements.
    resignAppPreservingEntitlements(app);
    signed += 1;
  }
  if (signed === 0) {
    console.log('[face-recognition-cordova] note: no built frameworks found to re-sign yet');
  }
}


function prepare(projectRoot) {
  const platformsIos = path.join(projectRoot, 'platforms', 'ios');
  if (!fs.existsSync(platformsIos)) return;
  const teamId = readTeamId(projectRoot);
  writeExtras(projectRoot, teamId);
  writeSignScript(platformsIos);
  // Fix Cordova-copied frameworks before xcodebuild embeds them.
  syncPluginFrameworks(projectRoot);
  fixIosSymlinks(projectRoot);
  console.log(
    `[face-recognition-cordova] iOS extras: team=${teamId || '(none)'} bundle=${IOS_BUNDLE_ID}`
  );
}


module.exports = function (ctx) {
  const projectRoot =
    (ctx && ctx.opts && ctx.opts.projectRoot) ||
    process.argv[2] ||
    process.cwd();
  const hook = String(
    (ctx && (ctx.hook || ctx.type)) ||
      (ctx && ctx.opts && ctx.opts.hook) ||
      ''
  );
  prepare(projectRoot);
  if (hook.includes('after_build') || process.argv.includes('--sign')) {
    signBuiltApps(projectRoot);
  }
};


if (require.main === module) {
  const root = process.argv[2] || process.cwd();
  prepare(root);
  if (process.argv.includes('--sign')) signBuiltApps(root);
}
